//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoinTelcoServicesTest.ServiceJoinTelco {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadLineasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_clientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_documentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int clienteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadLineas {
            get {
                return this.CantidadLineasField;
            }
            set {
                if ((this.CantidadLineasField.Equals(value) != true)) {
                    this.CantidadLineasField = value;
                    this.RaisePropertyChanged("CantidadLineas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCliente {
            get {
                return this.EstadoClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoClienteField, value) != true)) {
                    this.EstadoClienteField = value;
                    this.RaisePropertyChanged("EstadoCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_client {
            get {
                return this.Nombre_clientField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_clientField, value) != true)) {
                    this.Nombre_clientField = value;
                    this.RaisePropertyChanged("Nombre_client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_documento {
            get {
                return this.Num_documentoField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_documentoField, value) != true)) {
                    this.Num_documentoField = value;
                    this.RaisePropertyChanged("Num_documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int clienteId {
            get {
                return this.clienteIdField;
            }
            set {
                if ((this.clienteIdField.Equals(value) != true)) {
                    this.clienteIdField = value;
                    this.RaisePropertyChanged("clienteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfClienteyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfClienteyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.Cliente dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.Cliente data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class ErroresException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfstring", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfArrayOfClienteyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfArrayOfClienteyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.Cliente[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.Cliente[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContratoCliente", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class ContratoCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cliente_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContratoClienteIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fecha_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumerocelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int plan_servicioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cliente_id {
            get {
                return this.Cliente_idField;
            }
            set {
                if ((this.Cliente_idField.Equals(value) != true)) {
                    this.Cliente_idField = value;
                    this.RaisePropertyChanged("Cliente_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContratoClienteId {
            get {
                return this.ContratoClienteIdField;
            }
            set {
                if ((this.ContratoClienteIdField.Equals(value) != true)) {
                    this.ContratoClienteIdField = value;
                    this.RaisePropertyChanged("ContratoClienteId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoContrato {
            get {
                return this.EstadoContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoContratoField, value) != true)) {
                    this.EstadoContratoField = value;
                    this.RaisePropertyChanged("EstadoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fecha_Registro {
            get {
                return this.Fecha_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Fecha_RegistroField, value) != true)) {
                    this.Fecha_RegistroField = value;
                    this.RaisePropertyChanged("Fecha_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numerocelular {
            get {
                return this.NumerocelularField;
            }
            set {
                if ((object.ReferenceEquals(this.NumerocelularField, value) != true)) {
                    this.NumerocelularField = value;
                    this.RaisePropertyChanged("Numerocelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int plan_servicioId {
            get {
                return this.plan_servicioIdField;
            }
            set {
                if ((this.plan_servicioIdField.Equals(value) != true)) {
                    this.plan_servicioIdField = value;
                    this.RaisePropertyChanged("plan_servicioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfContratoClienteyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfContratoClienteyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfPlan_Servicioyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfPlan_Servicioyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.Plan_Servicio dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.Plan_Servicio data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Plan_Servicio", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Plan_Servicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Plan_ServicioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_servicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double precio_servicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Plan_ServicioId {
            get {
                return this.Plan_ServicioIdField;
            }
            set {
                if ((this.Plan_ServicioIdField.Equals(value) != true)) {
                    this.Plan_ServicioIdField = value;
                    this.RaisePropertyChanged("Plan_ServicioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre_servicio {
            get {
                return this.nombre_servicioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_servicioField, value) != true)) {
                    this.nombre_servicioField = value;
                    this.RaisePropertyChanged("nombre_servicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double precio_servicio {
            get {
                return this.precio_servicioField;
            }
            set {
                if ((this.precio_servicioField.Equals(value) != true)) {
                    this.precio_servicioField = value;
                    this.RaisePropertyChanged("precio_servicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.Plan_Servicio[] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.Plan_Servicio[] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntentosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoUsuario {
            get {
                return this.CodigoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoUsuarioField, value) != true)) {
                    this.CodigoUsuarioField = value;
                    this.RaisePropertyChanged("CodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaUsuario {
            get {
                return this.ContrasenaUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaUsuarioField, value) != true)) {
                    this.ContrasenaUsuarioField = value;
                    this.RaisePropertyChanged("ContrasenaUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Intentos {
            get {
                return this.IntentosField;
            }
            set {
                if ((this.IntentosField.Equals(value) != true)) {
                    this.IntentosField = value;
                    this.RaisePropertyChanged("Intentos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfboolean", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool data {
            get {
                return this.dataField;
            }
            set {
                if ((this.dataField.Equals(value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordResponseObjectOfUsuarioyy3A9QwE", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class RecordResponseObjectOfUsuarioyy3A9QwE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JoinTelcoServicesTest.ServiceJoinTelco.Usuario dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JoinTelcoServicesTest.ServiceJoinTelco.Usuario data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceJoinTelco.IJoinTelcoServices")]
    public interface IJoinTelcoServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/RegistrarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/RegistrarClienteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JoinTelcoServicesTest.ServiceJoinTelco.ErroresException), Action="http://tempuri.org/IJoinTelcoServices/RegistrarClienteErroresExceptionFault", Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE RegistrarCliente(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/RegistrarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> RegistrarClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE ObtenerCliente(string Num_documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> ObtenerClienteAsync(string Num_documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ModificarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ModificarClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE ModificarCliente(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ModificarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ModificarClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> ModificarClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/EliminarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/EliminarClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring EliminarCliente(string Num_documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/EliminarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/EliminarClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring> EliminarClienteAsync(string Num_documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ListarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ListarClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfClienteyy3A9QwE ListarCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ListarCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ListarClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfClienteyy3A9QwE> ListarClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/RegistrarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/RegistrarContratoClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE RegistrarContratoCliente(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/RegistrarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/RegistrarContratoClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> RegistrarContratoClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerContratoClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE ObtenerContratoCliente(string ContratoClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerContratoClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> ObtenerContratoClienteAsync(string ContratoClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ModificarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ModificarContratoClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE ModificarContratoCliente(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ModificarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ModificarContratoClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> ModificarContratoClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/EliminarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/EliminarContratoClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring EliminarContratoCliente(string ContratoClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/EliminarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/EliminarContratoClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring> EliminarContratoClienteAsync(string ContratoClienteId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ListarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ListarContratoClienteResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE ListarContratoCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ListarContratoCliente", ReplyAction="http://tempuri.org/IJoinTelcoServices/ListarContratoClienteResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE> ListarContratoClienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciobyId", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciobyIdResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfPlan_Servicioyy3A9QwE ObtenerPlanServiciobyId(int codigoPlanServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciobyId", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciobyIdResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfPlan_Servicioyy3A9QwE> ObtenerPlanServiciobyIdAsync(int codigoPlanServicio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServicios", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciosResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE ObtenerPlanServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServicios", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerPlanServiciosResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE> ObtenerPlanServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ValidarConexion", ReplyAction="http://tempuri.org/IJoinTelcoServices/ValidarConexionResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfboolean ValidarConexion(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ValidarConexion", ReplyAction="http://tempuri.org/IJoinTelcoServices/ValidarConexionResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfboolean> ValidarConexionAsync(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerUsuario", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerUsuarioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JoinTelcoServicesTest.ServiceJoinTelco.ErroresException), Action="http://tempuri.org/IJoinTelcoServices/ObtenerUsuarioErroresExceptionFault", Name="ErroresException", Namespace="http://schemas.datacontract.org/2004/07/WcfTelcoServices.Dominio")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE ObtenerUsuario(string codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ObtenerUsuario", ReplyAction="http://tempuri.org/IJoinTelcoServices/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE> ObtenerUsuarioAsync(string codigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ActualizarUsuario", ReplyAction="http://tempuri.org/IJoinTelcoServices/ActualizarUsuarioResponse")]
        JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE ActualizarUsuario(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJoinTelcoServices/ActualizarUsuario", ReplyAction="http://tempuri.org/IJoinTelcoServices/ActualizarUsuarioResponse")]
        System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE> ActualizarUsuarioAsync(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJoinTelcoServicesChannel : JoinTelcoServicesTest.ServiceJoinTelco.IJoinTelcoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JoinTelcoServicesClient : System.ServiceModel.ClientBase<JoinTelcoServicesTest.ServiceJoinTelco.IJoinTelcoServices>, JoinTelcoServicesTest.ServiceJoinTelco.IJoinTelcoServices {
        
        public JoinTelcoServicesClient() {
        }
        
        public JoinTelcoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JoinTelcoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoinTelcoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JoinTelcoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE RegistrarCliente(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente) {
            return base.Channel.RegistrarCliente(_cliente);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> RegistrarClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente) {
            return base.Channel.RegistrarClienteAsync(_cliente);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE ObtenerCliente(string Num_documento) {
            return base.Channel.ObtenerCliente(Num_documento);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> ObtenerClienteAsync(string Num_documento) {
            return base.Channel.ObtenerClienteAsync(Num_documento);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE ModificarCliente(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente) {
            return base.Channel.ModificarCliente(_cliente);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfClienteyy3A9QwE> ModificarClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.Cliente _cliente) {
            return base.Channel.ModificarClienteAsync(_cliente);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring EliminarCliente(string Num_documento) {
            return base.Channel.EliminarCliente(Num_documento);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring> EliminarClienteAsync(string Num_documento) {
            return base.Channel.EliminarClienteAsync(Num_documento);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfClienteyy3A9QwE ListarCliente() {
            return base.Channel.ListarCliente();
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfClienteyy3A9QwE> ListarClienteAsync() {
            return base.Channel.ListarClienteAsync();
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE RegistrarContratoCliente(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente) {
            return base.Channel.RegistrarContratoCliente(contratoCliente);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> RegistrarContratoClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente) {
            return base.Channel.RegistrarContratoClienteAsync(contratoCliente);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE ObtenerContratoCliente(string ContratoClienteId) {
            return base.Channel.ObtenerContratoCliente(ContratoClienteId);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> ObtenerContratoClienteAsync(string ContratoClienteId) {
            return base.Channel.ObtenerContratoClienteAsync(ContratoClienteId);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE ModificarContratoCliente(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente) {
            return base.Channel.ModificarContratoCliente(contratoCliente);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfContratoClienteyy3A9QwE> ModificarContratoClienteAsync(JoinTelcoServicesTest.ServiceJoinTelco.ContratoCliente contratoCliente) {
            return base.Channel.ModificarContratoClienteAsync(contratoCliente);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring EliminarContratoCliente(string ContratoClienteId) {
            return base.Channel.EliminarContratoCliente(ContratoClienteId);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfstring> EliminarContratoClienteAsync(string ContratoClienteId) {
            return base.Channel.EliminarContratoClienteAsync(ContratoClienteId);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE ListarContratoCliente() {
            return base.Channel.ListarContratoCliente();
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfContratoClienteyy3A9QwE> ListarContratoClienteAsync() {
            return base.Channel.ListarContratoClienteAsync();
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfPlan_Servicioyy3A9QwE ObtenerPlanServiciobyId(int codigoPlanServicio) {
            return base.Channel.ObtenerPlanServiciobyId(codigoPlanServicio);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfPlan_Servicioyy3A9QwE> ObtenerPlanServiciobyIdAsync(int codigoPlanServicio) {
            return base.Channel.ObtenerPlanServiciobyIdAsync(codigoPlanServicio);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE ObtenerPlanServicios() {
            return base.Channel.ObtenerPlanServicios();
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfArrayOfPlan_Servicioyy3A9QwE> ObtenerPlanServiciosAsync() {
            return base.Channel.ObtenerPlanServiciosAsync();
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfboolean ValidarConexion(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario) {
            return base.Channel.ValidarConexion(usuario);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfboolean> ValidarConexionAsync(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario) {
            return base.Channel.ValidarConexionAsync(usuario);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE ObtenerUsuario(string codigoUsuario) {
            return base.Channel.ObtenerUsuario(codigoUsuario);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE> ObtenerUsuarioAsync(string codigoUsuario) {
            return base.Channel.ObtenerUsuarioAsync(codigoUsuario);
        }
        
        public JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE ActualizarUsuario(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario) {
            return base.Channel.ActualizarUsuario(usuario);
        }
        
        public System.Threading.Tasks.Task<JoinTelcoServicesTest.ServiceJoinTelco.RecordResponseObjectOfUsuarioyy3A9QwE> ActualizarUsuarioAsync(JoinTelcoServicesTest.ServiceJoinTelco.Usuario usuario) {
            return base.Channel.ActualizarUsuarioAsync(usuario);
        }
    }
}
